modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="pasterdream"
version="0.3.5.7"
displayName="PasterDream"
displayURL="https://www.mcmod.cn/class/8530.html"
logoFile="logo.png"
credits="阿墨 夜岚风清  煮饭婆  初雪冰  Vittorio_Veneto  Fallen_sky2  幼幼紫"
authors="异星之尘"
description="测试版（未完工）"

[[dependencies.pasterdream]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.pasterdream]]
    modId="curios"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pasterdream]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pasterdream]]
    modId="playeranimator"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pasterdream]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pasterdream]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pasterdream]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

